### ISSUE TITLE
Files in webroot

### ISSUE THREAD

**Issue by ravage84** [CCadere/DocumentManager#1]
(Tried to answer you in your Bakery post http://bakery.cakephp.org/articles/ccadere/2013/07/18/document_manager_plugin_for_cakephp_2_x/comment:0#comments but only got "An Internal Error Has Occurred.")

Salut,

Did I understand that right that the files are stored in the webroot?
If that's the case then they will be served directly through the webserver without involving CakePHP.
This might be faster but I don't see how you can secure the files this way (through the CakePHP application).

Greetings from Switzerland
Marc

**Comment by CCadere** [comment]
Hey,
Yeah sadly in the bakery when you post a comment you get an internal 
server error even if the comment has actually been saved.... I wrote 
admin reporting this bug but is has not been fixed.

I replied on the article page for other persons having the same 
question. But here is a copy:

Hey,
Yeah, files are stored inside the webroot within a root directory that 
you specify.

The aim of the plugin is not to replace the webserver, but to provide an 
UI to manage files directly in you browser, a bit like in a web FTP manager.

When you create a directory using the plugin, an index.php is created 
inside the new directory to prevent unwanted access.

Hope it answers your question !

**Comment by ravage84** [comment]
Well yes this answers my question but the problem I have remains.
I don't want a replacement for the webserver, but if I want to have an application that manages my documents I also want it to keep those files secure...

**Comment by CCadere** [comment]
This plugin is designed to be easily hooked up with a user management and user permission system like Authake. Once hooked up, the plugin manages user permissions for uploaded files preventing users to delete other users files.

If you do not want to use a user management system, there are still simple permission systems like ACL or prefix rooting (in that case you would only have to update the name of the actions in controllers).

Otherwise if you do not handle users and permissions at all in your application, you can put a .htaccess requiring an authentification at the base of your Document Manager plugin.

But out of the box, it does not prevent visitors to access the URL corresponding to the plugin and browse the file architecture. That is not its purpose.
